### ISSUE TITLE
Adapt tools currently evaluated as needs are defined

### ISSUE THREAD

**Issue by gaurav** [cancerDHC/tools#10]

**Comment by gaurav** [comment]
I think this issue is too vague to put in an issue tracker, so we should probably remove it and then add in issues for actual tools as needed (e.g. CEDAR, Ptolemy, etc.). @balhoff What do you think?

**Comment by balhoff** [comment]
This was an example in the draft roadmap—will close and will add specific issues as requirements are defined.
