### ISSUE TITLE
Tools to enable stakeholders to implement CRDC-H (discussion with Seven Bridges, CDA)

### ISSUE THREAD

**Issue by gaurav** [cancerDHC/tools#11]

**Comment by gaurav** [comment]
I don't think we can do much about this until an early draft of CRDC-H is BiolinkML (after https://github.com/cancerDHC/data-model-harmonization/issues/9) is available. Hopefully this will be available in Q4, so I'll pull it to 2020Q4 rather than 2021Q1.

**Comment by balhoff** [comment]
I'm going to close this in favor of more specific tickets: #29, #31
