### ISSUE TITLE
Develop tools for metadata mapping, transformation and validation

### ISSUE THREAD

**Issue by gaurav** [cancerDHC/tools#13]
Scheduled: Q3 2020, Q4 2020, Q1 2020

- [x] Aligned based on stakeholder requirements
- [x] Focus on tools (or adjusted based on user needs)
  - [x] Metadata mapping and transformation tools
  - [x] Metadata validator
- [x] Tools needed specifically for development of CRDC-H

**Comment by llchristopherson** [comment]
Multiple steps involved with this...
1. Determine who = "stakeholder." Jim is working on a meeting to determine this.
2. Then identify user/stakeholder needs. Laura can do this. 
3. Then identify what tools should be built based on those needs. All 3 of us should confer on this.
4. Build the tools. That's Guarav and Jim.
5. Test/assess tools. Laura
6. Have users/stakeholders play with tools and give feedback. Laura can train users and get the feedback.
7. Make any needed improvements. Guarav and Jim.
8. Release first version.

**Comment by gaurav** [comment]
Updates: we have discussed this and decided that we have three levels of customers:
1. CCDH itself and our other workstreams
2. The CRDC Nodes, in particular CDA
3. Doctors, scientists, researchers and others using the CRDC

So I guess the question now is: what metadata mapping, transformation and validation needs does the CRDC and the nodes have? We will be organizing a meeting with the Terminologies workstream soon to see how we can support them. We are currently working with the Nodes on a concierge basis, and CCDH as a whole is currently working with CDA to identify a minimum viable product (#12). I'll leave this scheduled for 2021Q1, but I think we could have a few meetings about this and get a plan in place by the end of 2020Q3.

**Comment by balhoff** [comment]
Initial implementation of these are in https://github.com/cancerDHC/ccdhmodel and https://github.com/cancerDHC/example-data.
