### ISSUE TITLE
Choose a format for publishing harmonized datasets

### ISSUE THREAD

**Issue by gaurav** [cancerDHC/tools#15]
We currently have an initial, incomplete set of harmonized data from some IDC example datasets (#4), and need to chose a format to store and publish this data in a way that maintains provenance information. Here are some possible formats:
 - [CEDAR instances](https://github.com/metadatacenter/cedar-docs/wiki/CEDAR-Template,-Element,-and-Field-Instances)
 - [Portable Format for Biomedical Data (PFB)](https://github.com/uc-cdis/pypfb) (see also [the description on Bento-Meta](https://github.com/CBIIT/bento-meta/tree/948e17544660d1886b5beb3040edd63d8fce2af6/python/bento_meta/pfb#portable-format-for-bioinformatics))

Please feel free to add any other formats we should look at!

This issue covers comparing these formats for our purposes and to translate the incomplete harmonized data into that format as a potential exemplar.

**Comment by fedorov** [comment]
Before we answer this question - do you know where will the resulting files live within the CRDC? What resource is going to be responsible for supporting users in querying the data stored in those files?

**Comment by balhoff** [comment]
I think the answer to that lies in the ultimate architecture for CDA. Definitely the querying part; not sure about storage of the files.

**Comment by fedorov** [comment]
Since CDA was mentioned - adding @DavidPotCanuck who is one of the leads for CDA, in case he is interested to participate in this discussion.

**Comment by gaurav** [comment]
I've made a preliminary conversion from the [ISPY1 patient clinical subset](https://github.com/gaurav/csv2caDSR/blob/to-pfb/examples/ispy1/ISPY1-patient-clinical-subset.csv) to PFB by using a [JSON file that records the mappings](https://github.com/gaurav/csv2caDSR/blob/to-pfb/examples/ispy1/ISPY1-tcia-outcomes-subset-enumValues.json). You can [download the PFB file](https://github.com/gaurav/csv2caDSR/blob/to-pfb/examples/ispy1/ispy1.avro), or have a look at their internal representation extracted with the [PyPFB](https://github.com/uc-cdis/pypfb) tool: [the Avro schema](https://github.com/gaurav/csv2caDSR/blob/to-pfb/examples/ispy1/avro_components/ispy1_schema.json), [PFB metadata node](https://github.com/gaurav/csv2caDSR/blob/to-pfb/examples/ispy1/avro_components/ispy1_metadata.json), and [data](https://github.com/gaurav/csv2caDSR/blob/to-pfb/examples/ispy1/avro_components/ispy1_data.jsonl).

The good news is that PFB can be used to store textual, numerical and enumerated data, along with a reference to the caDSR CDE used for the mapping (from which we could map the harmonized values to NCIt concept identifiers). The bad news is that Avro fields and enum values are both restricted to the regex `[A-Za-z_][A-Za-z0-9_]*`. The PFB developers have come up with a simple representation for inserting Unicode characters (using e.g. `_00A9_` to represent U+00A9 = ©), but PyPFB  doesn't consistently translate those field names into and out of JSON at the moment. We could probably fix this without too much of a problem, assuming that this is a bug in PyPFB and not a misinterpretation on my part. PFB doesn't currently have a facility for storing verbatim values, so we do lose the actual values recorded in the original data. We might be able to propose a change to PFB to record this information if it is important to us. Another possibility is that we could store all the mapping information in another part of the Avro file, leave the verbatim values as-is and only convert them into harmonized values when exporting it.

I'm going to leave this conversion as-is for now and move on to trying to convert the same dataset into the CEDAR instance format so we can do a side-by-side comparison between these two formats.

**Comment by gaurav** [comment]
We'll have some example output files in https://github.com/cancerDHC/example-data/issues/10 -- we can use that to figure out which format work best for our needs.

**Comment by gaurav** [comment]
For our immediate needs, the LinkML instance format (in YAML) seems to be a good representation, and has been developed into [some exemplars](https://github.com/cancerDHC/data-model-harmonization/tree/79849628bca909ef113a6031bf1eb25498c48ee2/data-examples/f2f-2021-09-data-examples) by the CCDH Data Model Harmonization team as part of the CCDH Pilot. Future formats will probably be supported by adding generators to LinkML, so that data from any LinkML model can be converted into that format (e.g. see [the issue tracking an Avro/PFB generator for LinkML](https://github.com/linkml/linkml/issues/354)). Given that, I think we can close this issue until specific use-cases emerge from CDA and the CRDC nodes.
