### ISSUE TITLE
PDC: Biggest challenge is transforming source data to GDC or PDC data dictionary – tools for data transformation (structured format) will be useful 

### ISSUE THREAD

**Issue by llchristopherson** [cancerDHC/tools#18]
From Resham's https://docs.google.com/document/d/147oFEWeOzcUTkL6jFqd93Q6uO91D8Gvjpd-RGVMQ1LE/edit

**Comment by gaurav** [comment]
This need will be met by the Example Data Workflow (https://github.com/cancerDHC/tools/issues/36) -- since that issue is more detailed than this, I will close it here.
