### ISSUE TITLE
review of CDS data and think about how it would be used to inform the requirements

### ISSUE THREAD

**Issue by nicolevasilevsky** [cancerDHC/tools#2]
See Internal Team [notes from 2020-03-03](https://docs.google.com/document/d/18XyS8h0MeFYTLBAGlxXhhTmtgZ9yNyLIGJX1VIGdzwc/edit#bookmark=id.3m9uwxea9hf2), 'CDS prep notes and interview.'

You will need DBgap access.

**Comment by balhoff** [comment]
@mbrush this seems like a data model task. Do you have any further info about CDS and what we need to do here?

**Comment by balhoff** [comment]
@gaurav has consolidated CDS data dictionaries in these Google sheets:

https://docs.google.com/spreadsheets/d/1SwO8Vu7pljTDNkaWiEUtAwQCIZbdRn8N/edit#gid=409764493
https://docs.google.com/spreadsheets/d/1DPQEHAX8Su0Ae9Tx9pBLQH6wFXGVnTKK8P9rP9rg_oQ/edit#gid=409764493
https://docs.google.com/spreadsheets/d/1hZR9eLRH1h5G-X62-cwEgXLQfbTFtDESj_EHbmErnZk/edit#gid=188865801
