### ISSUE TITLE
define validation approach for using terminology value sets with linkml

### ISSUE THREAD

**Issue by balhoff** [cancerDHC/tools#30]
The validation runner needs to be able to interact with the terminology services to check if values adhere to a value set.

**Comment by gaurav** [comment]
We currently implement this by:
1. Retrieving all permissible values [from the Terminology Service](https://terminology.ccdh.io/docs#/Enumerations/get_enumeration) for a field (slot) when converting it from the Google Sheet representation into LinkML.
2. Adding them to the slot definition when generating LinkML.
3. Validating example data using Python Data Classes.

I think that's enough to consider this done for now. This will likely change in the future as our model generation workflow changes, but that's not something we can anticipate currently.
