### ISSUE TITLE
Incorporate ontologies into DICOM SNOMED to NCIt mapping

### ISSUE THREAD

**Issue by gaurav** [cancerDHC/tools#7]
We now [have an SSSOM file](https://docs.google.com/spreadsheets/d/150n_mnD2ZNvHvv1lMIK1zIlfv91ttcgU3B0JDvpzbBI/edit) containing mappings from DICOM SNOMED to NCIt using the NCI Metathesaurus as part of https://github.com/cancerDHC/operations/issues/48. In this issue, we will attempt to fill in the missing gaps by using terms from particular ontologies, in particular:
- [x] The EBI [Ontology Lookup Service](https://www.ebi.ac.uk/ols/)
- [x] [Livestock Breed Ontology](https://www.ebi.ac.uk/ols/ontologies/lbo)
- [x] [ChEBI](https://www.ebi.ac.uk/chebi/)
- [ ] [RadLex](http://radlex.org/)
- [ ] [AGROVOC](http://aims.fao.org/vest-registry/vocabularies/agrovoc)
- *(Any other suggestions?)*

**Comment by gaurav** [comment]
We now have the exact terms from:
 - ChEBI
 - Livestock Breed Ontology
 - The EBI [Ontology Lookup Service](https://www.ebi.ac.uk/ols/)

This puts us at 2,434 terms remaining to be matched. You can see the [mappings in the SSSOM file](https://docs.google.com/spreadsheets/d/18luA05E9wLukOFamsRV3FWVnoCr57o8qAHe-aGYrPr8/edit#gid=1976835818).

My immediate next step is to see if we can group the remaining terms in some way, perhaps by looking at the hierarchical information in the NCImt. That might make it easier to figure out how to go about mapping the remaining terms.

**Comment by gaurav** [comment]
Added RadLex to the list as mentioned in https://github.com/cancerDHC/operations/issues/48#issuecomment-694868279.

**Comment by balhoff** [comment]
Since individual ontologies can be tackled as separable work items, I created #19 and will close this issue. I also created #20 for exploring use of NCImt hierarchy to aid mapping by grouping terms.
